apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    app: website
    service: website
spec:
  type: ClusterIP
  selector:
    app: website
  ports: 
    - targetPort: 80
      port: 80