apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
      version: v1
  template:
    metadata:
      labels:
        app: website
        version: v1
    spec:
      containers:
      - name: website
        image: registry.digitalocean.com/hometest/website:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: 2Gi
            cpu: "1"
          requests:
            memory: 1Gi
            cpu: "1"
      imagePullSecrets:
        - name: regcred

