apiVersion: v1
kind: Secret
metadata:
  name: system-secret
type: Opaque
data:
  LLM_KEY: c2stdGFqYmhNdnhjTnFlUVdETU1PRUdUM0JsYmtGSlk4Z012M1BueTF3SGFRMWtwQk5X
  LLM_MODEL: ZnQ6Z3B0LTMuNS10dXJiby0wNjEzOmFpNHM6cGRtOjd5TDdtdnFj
