apiVersion: v1
kind: Service
metadata:
  name: platform
  labels:
    app: platform
    service: platform
spec:
  type: ClusterIP
  selector:
    app: platform
  ports: 
    - targetPort: 8000
      port: 80