apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
  labels:
    app: platform
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform
      version: v1
  template:
    metadata:
      labels:
        app: platform
        version: v1
    spec:
      containers:
      - name: platform
        image: registry.digitalocean.com/hometest/hometest:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        command: ["gunicorn", "--bind","0:8000","wsgi:app"]
        env:
        - name: LLM_KEY
          valueFrom:
            secretKeyRef:
              name: system-secret
              key: LLM_KEY
        - name: LLM_MODEL
          valueFrom:
            secretKeyRef:
              name: system-secret
              key: LLM_MODEL
        resources:
          limits:
            memory: 2Gi
            cpu: "1"
          requests:
            memory: 1Gi
            cpu: "1"
      imagePullSecrets:
        - name: regcred

